version: "0.2"

env:
  shell: bash

phases:
  build:
    commands:
      - cd demo-app
      - export TRUNK_BUILD_RELEASE=true
      - trunk build
      - cd dist

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - $HOME/.cargo/registry/**/*
    